#!/usr/bin/env bash
# https://github.com/versus-systems/kubecmd

namespace=default
deployment=""

while getopts n:d: name
  do
    case $name in
      n) namespace="$OPTARG";;
      d) deployment_name="$OPTARG";;
    esac
done

if [[ -z $deployment_name ]]; then
  cat << USAGE
    You need to specify a deployment name and a namespace.
    It defaults to default's namespace.

    usage:
      kubecmd -d <deployment name> -n <namespace> <command>

    e.g.
    kubecmd -d my-rails-app -n develop rails console  => open up a rails console
    kubecmd -d my-rails-app -n develop /bin/sh        => ssh into my-rails-app
USAGE
exit 2
fi

shift $(expr $OPTIND - 1 )
command=$@

container=$(kubectl get deployment $deployment_name --namespace $namespace -o json \
  | jq '.spec.template.spec.containers[0].command = ["sleep", "1d"]' \
  | jq 'del(.spec.template.spec.containers[0].livenessProbe)' \
  | jq 'del(.spec.template.spec.containers[0].readinessProbe)' \
  | jq '.spec.template.spec.containers[0]')

job_name="${deployment_name}-cmd-$RANDOM"

kubectl create --namespace $namespace -f - <<-JOB
{
  "apiVersion": "batch/v1",
  "kind": "Job",
  "metadata": {
    "name": "$job_name",
    "labels": {
      "app": "cmd"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "labels": {
          "job": "$job_name"
        }
      },
      "spec": {
        "restartPolicy": "Never",
        "containers": [$container]
      }
    }
  }
}
JOB

printf "connecting ."

pod_name=$(kubectl get pod -n $namespace -l job=$job_name -o jsonpath="{.items[0].metadata.name}")

while [[ $(kubectl get pod $pod_name -n $namespace -o jsonpath="{..status.containerStatuses[0].ready}") != "true" ]]; do
  printf "."
  sleep 1
done

kubectl exec -it --namespace $namespace $pod_name $command
kubectl delete job $job_name --namespace $namespace
